# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
# https://eth-brownie.readthedocs.io/en/stable/config.html
network:
  default: development # the default network that brownie connects to
  settings:
    gas_limit: "auto"
    gas_price: "auto"
    persist: true
    reverting_tx_gas_limit: false # if false, reverting tx's will raise without broadcasting
  networks:
    # any settings given here will replace the defaults
    development:
      host: http://127.0.0.1
      gas_price: 0
      persist: false
      reverting_tx_gas_limit: 6721975
      test_rpc:
        cmd: ganache-cli
        port: 8545
        gas_limit: 6721975
        accounts: 10
        evm_version: istanbul
        mnemonic: brownie
    # set your Infura API token to the environment variable WEB3_INFURA_PROJECT_ID
    mainnet:
      host: https://mainnet.infura.io/v3/$WEB3_INFURA_PROJECT_ID
    goerli:
      host: https://goerli.infura.io/v3/$WEB3_INFURA_PROJECT_ID
    kovan:
      host: https://kovan.infura.io/v3/$WEB3_INFURA_PROJECT_ID
    rinkeby:
      host: https://eth-rinkeby.alchemyapi.io/v2/GpWPWBydA0IPwd3H7CPM_nA3RwRxvl3S
    ropsten:
      host: https://ropsten.infura.io/v3/$WEB3_INFURA_PROJECT_ID
    classic:
      host: https://www.ethercluster.com/etc
    kotti:
      host: https://www.ethercluster.com/kotti
